covid_web_app/main/routes.py
from flask import render_template, Blueprint, redirect, url_for, request
from flask_login import login_required
from datetime import date
from .forms import DailyUpdateForm
from .. import db
from ..models import User, Relationship
from ..core import daily_update as core_daily_update

main = Blueprint('main', __name__)


@main.route("/")
def home():
    return render_template('main/home.html')


@main.route("/privacy")
def privacy():
    return render_template('main/privacy.html', title='Privacy')


@main.route("/about")
def about():
    return render_template('main/about.html', title='About')


# Only for the development version
@main.route("/a_day_passes", methods=['GET', 'POST'])
@login_required
def daily_update():
    update_form = DailyUpdateForm()

    if request.method == 'POST' and update_form.validate_on_submit():
        user_to_delete, rs_to_delete = core_daily_update(User.query.all(), Relationship.query.all(), update_form.today_date.data)
        for cur_user in user_to_delete:
            db.session.delete(cur_user)
        for cur_rs in rs_to_delete:
            db.session.delete(cur_rs)
        db.session.commit()

        return redirect(url_for('relationships.user_contacts'))
    elif request.method == 'GET':
        update_form.today_date.data = date.today()

    return render_template('main/a_day_passes.html', title='Daily update', update_form=update_form)

covid_web_app/users/routes.py
from flask import render_template, Blueprint, url_for, flash, redirect, abort, request, session, g, current_app
from flask_login import login_user, current_user, logout_user, login_required
from .forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm,\
    UpdateAccountForm, CreateSubAccountForm
from .utils import send_reset_email, get_children_recursive
from .. import db, app_bcrypt
from ..models import User
from ..config import python_ver
from ..core import create_user, delete_user

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if g.cur_user:
        return redirect(url_for('relationships.user_contacts'))

    form = RegistrationForm()
    if form.validate_on_submit():
        if python_ver == 3.9:
            hashed_password = app_bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        else:
            hashed_password = app_bcrypt.generate_password_hash(form.password.data)
        new_user = create_user(username=form.username.data, email=form.email.data,
                               postal_code=form.postal_code.data, hashed_password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))

    return render_template('users/register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if g.cur_user:
        return redirect(url_for('relationships.user_contacts'))

    form = LoginForm()
    if form.validate_on_submit():
        if form.email.data.isnumeric():
            user = User.query.get(form.email.data)
            if user.email:
                user = None
        else:
            user = User.query.filter_by(email=form.email.data).first()
        if user and app_bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('relationships.user_contacts'))

        if user and not user.password:
            flash('You can access your account only through your parent account.', 'info')
        else:
            flash('Login Unsuccessful. Please check email and password.', 'danger')

    return render_template('users/login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    session.pop('cur_user_id', None)
    session.pop('have_parent_access', None)

    return redirect(url_for('main.home'))


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if g.cur_user:
        return redirect(url_for('relationships.user_contacts'))
    if '@' not in current_app.config['MAIL_USERNAME']:
        flash("This web app didn't configure an email address.", 'danger')
        return redirect(url_for('users.login'))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))

    return render_template('users/reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if g.cur_user:
        return redirect(url_for('relationships.user_contacts'))

    user = User.verify_reset_token(token)

    if user is None:
        flash('That is an invalid or expired token.', 'warning')
        return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        if python_ver == 3.9:
            hashed_password = app_bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        else:
            hashed_password = app_bcrypt.generate_password_hash(form.password.data)
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))

    return render_template('users/reset_token.html', title='Reset Password', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.username.data:          g.cur_user.username = form.username.data
        if form.email.data:             g.cur_user.email = form.email.data
        if form.postal_code.data:       g.cur_user.postal_code = form.postal_code.data
        if form.password.data:
            if python_ver == 3.9:
                hashed_password = app_bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            else:
                hashed_password = app_bcrypt.generate_password_hash(form.password.data)
            g.cur_user.password = hashed_password
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = g.cur_user.username
        form.email.data = g.cur_user.email
        form.postal_code.data = g.cur_user.postal_code
        children_list = get_children_recursive(g.cur_user)

    return render_template('users/account.html', title='Account', form=form, children_list=children_list)


@users.route("/delete_account", methods=['POST'])
@login_required
def delete_account():
    if g.cur_user == current_user:
        logout_user()
        flash('Your account has been deleted!', 'info')
    else:
        session['cur_user_id'] = g.cur_user.parent_id
        flash("'" + g.cur_user.username + "' account has been deleted!", 'info')

    session.pop('have_parent_access', None)
    deleted_user = delete_user(g.cur_user, get_children_recursive(g.cur_user))
    if deleted_user:
        db.session.delete(deleted_user)
        db.session.commit()

    return redirect(url_for('main.home'))


@users.route("/sub_accounts")
@login_required
def sub_accounts():
    return render_template('users/sub_accounts.html', title='Sub-accounts',
                           get_children_recursive=get_children_recursive)


@users.route("/create_sub_account", methods=['GET', 'POST'])
@login_required
def create_sub_account():
    form = CreateSubAccountForm()
    if form.validate_on_submit():
        if form.password.data:
            if python_ver == 3.9:
                hashed_password = app_bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            else:
                hashed_password = app_bcrypt.generate_password_hash(form.password.data)
        else:
            hashed_password = ''
        new_user = create_user(username=form.username.data, email=form.email.data, postal_code=form.postal_code.data,
                               hashed_password=hashed_password, parent=g.cur_user)
        db.session.add(new_user)
        db.session.commit()
        flash("'" + new_user.username + "' account has been created!", 'success')
        return redirect(url_for('users.sub_accounts'))

    return render_template('users/create_sub_account.html', title='Create Sub-Account', form=form)


@users.route("/go_to_sub_account/<int:child_id>")
@login_required
def got_to_sub_account(child_id):
    if child_id < 0 or child_id >= len(g.cur_user.children):
        abort(403)

    session['cur_user_id'] = g.cur_user.children[child_id].id
    session['have_parent_access'] = True

    return redirect(url_for('relationships.user_contacts'))


@users.route("/go_to_parent_account")
@login_required
def go_to_parent_account():
    if not g.have_parent_access:
        abort(403)

    session['cur_user_id'] = g.cur_user.parent.id
    session.pop('have_parent_access', None)

    return redirect(url_for('relationships.user_contacts'))


@users.route("/delete_sub_account/<int:child_id>", methods=['POST'])
@login_required
def delete_sub_account(child_id):
    if child_id < 0 or child_id >= len(g.cur_user.children):
        abort(403)

    deleted_user = g.cur_user.children[child_id]
    deleted_user = delete_user(deleted_user, get_children_recursive(deleted_user))
    if deleted_user:
        db.session.delete(deleted_user)
        db.session.commit()

    return redirect(url_for('users.sub_accounts'))


@users.route("/detach_sub_account/<int:child_id>", methods=['POST'])
@login_required
def detach_sub_account(child_id):
    if child_id < 0 or child_id >= len(g.cur_user.children):
        abort(403)

    cur_child = g.cur_user.children[child_id]
    if cur_child.email and cur_child.password:
        cur_child.parent_id = None
        db.session.commit()

    return redirect(url_for('users.sub_accounts'))

covid_web_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    {% if title %}
        <title>My Web App - {{ title }}</title>
    {% else %}
        <title>My Web App</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Web App</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.privacy') }}">Privacy</a>
                    <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if g.cur_user %}
                        {% if g.have_parent_access %}
                            <a class="nav-item nav-link" href="{{ url_for('users.go_to_parent_account') }}">Parent account</a>
                        {% endif %}
                        <a class="nav-item nav-link" href="{{ url_for('users.sub_accounts') }}">Sub-accounts</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
        {% if g.cur_user %}
            <div class="col-md-4">
              <div class="content-section">
                <h3>Dashboard</h3>
                <p class='text-muted'>
                  <ul class="list-group">
                    <li class="list-group-item list-group-item-light"><a href="{{ url_for('relationships.user_contacts') }}">Your status and contacts</a></li>
                    <!--<li class="list-group-item list-group-item-light"><a href="#">Contact requests</a></li>
                    <li class="list-group-item list-group-item-light"><a href="#">Map</a></li>-->
                    <li class="list-group-item list-group-item-light"><a href="{{ url_for('main.daily_update') }}">A day passes... (test)</a></li>
                  </ul>
                </p>
              </div>
            </div>
        {% endif %}
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% block script %}{% endblock %}
</body>
</html>