covid_web_app/relationships/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, SubmitField, IntegerField, StringField
from wtforms.validators import DataRequired
from ..form_validator import username_length, check_username_id, check_contact_duplicate


class UserStateUpdateForm(FlaskForm):
    has_covid = BooleanField('You are positive to COVID')
    is_sick = BooleanField("You are feeling sick but it may not be COVID")
    has_recovered = BooleanField('You got COVID and you recovered')
    is_vaccinated = BooleanField('You are vaccinated against COVID')
    user_submit = SubmitField('Update status')


class CreateRelationshipForm(FlaskForm):
    user_id = IntegerField('Account ID', validators=[DataRequired(), check_contact_duplicate])
    username = StringField('Username', validators=[DataRequired(), username_length, check_username_id('user_id')])
    regular_contact = BooleanField('I will see him/her every few days')
    rs_submit = SubmitField('Add contact')


class ChangeMeetingTimeForm(FlaskForm):
    refresh_time = BooleanField('I met him/her today')
    regular_contact = BooleanField('I see him/her every few days')
    form_submit = SubmitField('Submit')

covid_web_app/relationships/routes.py
from flask import Blueprint, render_template, g, request, abort, url_for, redirect
from flask_login import login_required
from sqlalchemy import or_
from .forms import UserStateUpdateForm, CreateRelationshipForm, ChangeMeetingTimeForm
from .message import user_state_message, get_contact_info, get_meeting_time_string
from .. import db
from ..models import User, Relationship
from ..core import create_relationship, delete_relationship, user_get_info, user_set_state, rs_get_info,\
    set_meeting_day_now, set_regular_contact

relationships = Blueprint('relationships', __name__)


@relationships.route("/user_contacts", methods=['GET', 'POST'])
@login_required
def user_contacts():
    user_form = UserStateUpdateForm()
    rs_form = CreateRelationshipForm()
    show_rs_modal = False
    if request.method == 'POST':

        if user_form.user_submit.data and user_form.validate_on_submit():
            user_set_state(g.cur_user,
                           user_form.has_covid.data, user_form.is_sick.data,
                           user_form.has_recovered.data, user_form.is_vaccinated.data)
            db.session.commit()

        if rs_form.rs_submit.data:
            if rs_form.validate_on_submit():
                other_user = User.query.get(rs_form.user_id.data)
                new_rs = create_relationship(user_1=g.cur_user, user_2=other_user)
                set_regular_contact(new_rs, rs_form.regular_contact.data)
                db.session.add(new_rs)
                db.session.commit()

                rs_form.user_id.data = None
                rs_form.username.data = None

            elif rs_form.is_submitted():
                show_rs_modal = True

    elif request.method == 'GET':
        user_info = user_get_info(g.cur_user.user_state)
        user_form.has_covid.data = user_info.has_covid
        user_form.is_sick.data = user_info.is_sick
        user_form.has_recovered.data = user_info.has_recovered
        user_form.is_vaccinated.data = user_info.is_vaccinated

        rs_form.regular_contact.data = False

    user_message = user_state_message(g.cur_user.user_state)

    contact_list = db.session.query(User, Relationship).\
        filter(or_(Relationship.user_1_id == g.cur_user.id, Relationship.user_2_id == g.cur_user.id)).\
        join(User, or_(User.id == Relationship.user_1_id, User.id == Relationship.user_2_id)).\
        filter(User.id != g.cur_user.id).\
        order_by(User.username).all()

    contact_info = (get_contact_info(g.cur_user.user_state, cur_contact[0].user_state, cur_contact[1].rs_state)
                    for cur_contact in contact_list)

    return render_template("relationships/user_contacts.html", title="User & Contacts", user_message=user_message,
                           user_form=user_form, rs_form=rs_form, show_rs_modal=show_rs_modal,
                           contact_list_info=zip(contact_list, contact_info))


@relationships.route("/contact/<int:rs_id>", methods=['GET', 'POST'])
@login_required
def contact_detail(rs_id):
    cur_rs = Relationship.query.get(rs_id)

    cur_contact = None
    if cur_rs:
        if cur_rs.user_1 == g.cur_user:
            cur_contact = cur_rs.user_2
        elif cur_rs.user_2 == g.cur_user:
            cur_contact = cur_rs.user_1

    if cur_contact is None:
        abort(403)

    meeting_form = ChangeMeetingTimeForm()

    if request.method == 'POST':
        if meeting_form.validate_on_submit():
            set_regular_contact(cur_rs, meeting_form.regular_contact.data)
            if not meeting_form.regular_contact.data and meeting_form.refresh_time.data:
                set_meeting_day_now(cur_rs)
            db.session.commit()

    rs_info = rs_get_info(cur_rs.rs_state)
    meeting_form.regular_contact.data = rs_info.regular_contact
    meeting_form.refresh_time.data = False

    contact_info = get_contact_info(g.cur_user.user_state, cur_contact.user_state, cur_rs.rs_state)
    last_meeting_str = get_meeting_time_string(cur_rs)

    return render_template("relationships/contact_detail.html", title="Contact", cur_contact=cur_contact, rs_id=cur_rs.id,
                           contact_info=contact_info, last_meeting_str=last_meeting_str, meeting_form=meeting_form)


@relationships.route("/delete_contact/<int:rs_id>", methods=['POST'])
@login_required
def delete_contact(rs_id):
    del_rs = Relationship.query.get(rs_id)
    if not (del_rs and (del_rs.user_1 == g.cur_user or del_rs.user_2 == g.cur_user)):
        abort(403)

    del_rs = delete_relationship(del_rs)
    if del_rs:
        db.session.delete(del_rs)
    db.session.commit()

    return redirect(url_for('relationships.user_contacts'))

covid_web_app/templates/relationships/contact_detail.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h2 class="account-heading">{{ cur_contact.username }}</h2>
        <form method="POST" action="">
            {{ meeting_form.hidden_tag() }}
            <div class="form-group">
                {% for cur_symbol in contact_info %}
                    <i class="{{ cur_symbol.s_class }}" style="{{ cur_symbol.s_style }}"></i><p style="display:inline">&emsp;{{ cur_symbol.description }}</p><br>
                {% endfor %}
                <br>
                <p>{{ last_meeting_str }}</p>
                <div class="form-check-inline">
                  {{ meeting_form.refresh_time(class="form-check-input") }}
                  {{ meeting_form.refresh_time.label(class="form-check-label") }}
                </div><br>
                <div class="form-check-inline">
                  {{ meeting_form.regular_contact(class="form-check-input", onclick="DisableCheckbox()") }}
                  {{ meeting_form.regular_contact.label(class="form-check-label") }}
                </div><br>
                {{ meeting_form.form_submit(class="btn btn-primary btn-sm m-1") }}
            </div>
            <div class="form-group">
                <a class="btn btn-primary btn-sm m-1" href="{{ url_for('relationships.user_contacts') }}" role="button">Back to Contacts</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete Contact</button>
            </div>
        </form>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Contact?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('relationships.delete_contact', rs_id=rs_id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        DisableCheckbox() ;

        function DisableCheckbox() {
            var in_checkbox = document.getElementById("{{ meeting_form.regular_contact.id }}") ;
            var out_checkbox = document.getElementById("{{ meeting_form.refresh_time.id }}") ;

            out_checkbox.disabled = in_checkbox.checked ;
            if (in_checkbox.checked == true){
                out_checkbox.checked = true ;
            }
        }
    </script>
{% endblock %}

covid_web_app/templates/relationships/user_contacts.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h2 class="account-heading border-bottom pb-3">{{ g.cur_user.username }}</h2>
        {% for cur_message in user_message %}
            <h5 class="mt-4">{{ cur_message[0] }}</h5>
            {% for cur_sub_message in cur_message[1:] %}
                <p>{{ cur_sub_message }}</p>
            {% endfor %}
        {% endfor %}

        <button type="button" class="btn btn-primary btn-sm m-1" data-toggle="modal" data-target="#updateModal">Update status</button>
    </div>

    <div class="content-section">
        <h2 class="account-heading border-bottom pb-3">Your contacts</h2>
        {% if contact_list_info %}
            <ul class="list-group list-group-flush">
                {% for cur_user, cur_info in contact_list_info %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a class="h3" style="text-decoration: none; color: inherit;" href="{{ url_for('relationships.contact_detail', rs_id=cur_user[1].id) }}"> {{ cur_user[0].username }}</a>
                        <span class="pull-right">
                            {% for cur_symbol in cur_info %}
                                <i class="{{ cur_symbol.s_class }}" style="{{ cur_symbol.s_style }}" title="{{ cur_symbol.description }}"></i>
                            {% endfor %}
                        </span>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <h3>No contact</h3>
        {% endif %}

        <button type="button" class="btn btn-primary btn-sm m-1" data-toggle="modal" data-target="#contactModal">Add contact</button>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="POST" action="">
            {{ user_form.hidden_tag() }}
              <div class="modal-header">
                <h5 class="modal-title" id="updateModalLabel">Update your status</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                  <fieldset class="form-group">
                      <div class="form-check-inline">
                          {{ user_form.has_covid(class="form-check-input") }}
                          {{ user_form.has_covid.label(class="form-check-label") }}
                      </div><br>
                      <div class="form-check-inline">
                          {{ user_form.is_sick(class="form-check-input") }}
                          {{ user_form.is_sick.label(class="form-check-label") }}
                      </div><br>
                      <div class="form-check-inline">
                          {{ user_form.has_recovered(class="form-check-input") }}
                          {{ user_form.has_recovered.label(class="form-check-label") }}
                      </div><br>
                      <div class="form-check-inline">
                          {{ user_form.is_vaccinated(class="form-check-input") }}
                          {{ user_form.is_vaccinated.label(class="form-check-label") }}
                      </div>
                  </fieldset>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                {{ user_form.user_submit(class="btn btn-primary") }}
              </div>
            </form>
        </div>
      </div>
    </div>

<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="POST" action="">
            {{ rs_form.hidden_tag() }}
              <div class="modal-header">
                <h5 class="modal-title" id="contactModalLabel">Add a new contact</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                  <fieldset class="form-group">
                      <div class="form-group">
                            {{ rs_form.user_id.label(class="form-control-label") }}
                            {% if rs_form.user_id.errors %}
                                {{ rs_form.user_id(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in rs_form.user_id.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ rs_form.user_id(class="form-control form-control-lg") }}
                            {% endif %}
                      </div>
                      <div class="form-group">
                            {{ rs_form.username.label(class="form-control-label") }}
                            {% if rs_form.username.errors %}
                                {{ rs_form.username(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in rs_form.username.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ rs_form.username(class="form-control form-control-lg") }}
                            {% endif %}
                      </div>
                      <div class="form-check-inline">
                          {{ rs_form.regular_contact(class="form-check-input", onclick="DisableCheckbox()") }}
                          {{ rs_form.regular_contact.label(class="form-check-label") }}
                      </div><br>
                  </fieldset>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                {{ rs_form.rs_submit(class="btn btn-primary") }}
              </div>
            </form>
        </div>
      </div>
    </div>

{% endblock %}

{% block script %}
    {% if show_rs_modal %}
        <script>
            $('#contactModal').modal('show')
        </script>
    {% endif %}
{% endblock %}