covid_web_app/users/forms.py
from flask_wtf import FlaskForm
from flask_login import current_user
from wtforms import StringField, PasswordField, SubmitField, IntegerField, BooleanField
from wtforms.validators import DataRequired, Email, EqualTo, Optional
from ..form_validator import username_length, email_length, email_unique, postal_code_range


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), username_length])
    email = StringField('Email', validators=[DataRequired(), Email(), email_length, email_unique])
    postal_code = IntegerField('Postal code (numeric only)', validators=[DataRequired(), postal_code_range])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')


class LoginForm(FlaskForm):
    email = StringField('Email or Account ID if no email address', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')


class RequestResetForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Request')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')


class UpdateAccountForm(FlaskForm):
    username = StringField('Username', validators=[Optional(strip_whitespace=False), username_length])
    email = StringField('Email', validators=[Optional(strip_whitespace=False), Email(), email_length])
    postal_code = IntegerField('Postal code', validators=[Optional(strip_whitespace=False), postal_code_range])
    password = PasswordField('Password')
    confirm_password = PasswordField('Confirm Password', validators=[EqualTo('password')])
    submit = SubmitField('Update')

    def validate_email(self, email):
        if email.data != current_user.email:
            email_unique(self, email)


class CreateSubAccountForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), username_length])
    email = StringField('Email (Optional)', validators=[Optional(strip_whitespace=False), Email(),
                                                        email_length, email_unique])
    postal_code = IntegerField('Postal code (Numeric only)', validators=[DataRequired(), postal_code_range])
    password = PasswordField('Password (Optional)', validators=[Optional(strip_whitespace=False)])
    confirm_password = PasswordField('Confirm Password', validators=[EqualTo('password')])
    submit = SubmitField('Create account')

covid_web_app/users/routes.py
from flask import render_template, Blueprint, url_for, flash, redirect, abort, request, session, g, current_app
from flask_login import login_user, current_user, logout_user, login_required
from .forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm,\
    UpdateAccountForm, CreateSubAccountForm
from .utils import send_reset_email, get_children_recursive
from .. import db, app_bcrypt
from ..models import User
from ..config import python_ver
from ..core import create_user, delete_user

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if g.cur_user:
        return redirect(url_for('relationships.user_contacts'))

    form = RegistrationForm()
    if form.validate_on_submit():
        if python_ver == 3.9:
            hashed_password = app_bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        else:
            hashed_password = app_bcrypt.generate_password_hash(form.password.data)
        new_user = create_user(username=form.username.data, email=form.email.data,
                               postal_code=form.postal_code.data, hashed_password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))

    return render_template('users/register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if g.cur_user:
        return redirect(url_for('relationships.user_contacts'))

    form = LoginForm()
    if form.validate_on_submit():
        if form.email.data.isnumeric():
            user = User.query.get(form.email.data)
            if user.email:
                user = None
        else:
            user = User.query.filter_by(email=form.email.data).first()
        if user and app_bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('relationships.user_contacts'))

        if user and not user.password:
            flash('You can access your account only through your parent account.', 'info')
        else:
            flash('Login Unsuccessful. Please check email and password.', 'danger')

    return render_template('users/login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    session.pop('cur_user_id', None)
    session.pop('have_parent_access', None)

    return redirect(url_for('main.home'))


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if g.cur_user:
        return redirect(url_for('relationships.user_contacts'))
    if '@' not in current_app.config['MAIL_USERNAME']:
        flash("This web app didn't configure an email address.", 'danger')
        return redirect(url_for('users.login'))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))

    return render_template('users/reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if g.cur_user:
        return redirect(url_for('relationships.user_contacts'))

    user = User.verify_reset_token(token)

    if user is None:
        flash('That is an invalid or expired token.', 'warning')
        return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        if python_ver == 3.9:
            hashed_password = app_bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        else:
            hashed_password = app_bcrypt.generate_password_hash(form.password.data)
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))

    return render_template('users/reset_token.html', title='Reset Password', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.username.data:          g.cur_user.username = form.username.data
        if form.email.data:             g.cur_user.email = form.email.data
        if form.postal_code.data:       g.cur_user.postal_code = form.postal_code.data
        if form.password.data:
            if python_ver == 3.9:
                hashed_password = app_bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            else:
                hashed_password = app_bcrypt.generate_password_hash(form.password.data)
            g.cur_user.password = hashed_password
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = g.cur_user.username
        form.email.data = g.cur_user.email
        form.postal_code.data = g.cur_user.postal_code
        children_list = get_children_recursive(g.cur_user)

    return render_template('users/account.html', title='Account', form=form, children_list=children_list)


@users.route("/delete_account", methods=['POST'])
@login_required
def delete_account():
    if g.cur_user == current_user:
        logout_user()
        flash('Your account has been deleted!', 'info')
    else:
        session['cur_user_id'] = g.cur_user.parent_id
        flash("'" + g.cur_user.username + "' account has been deleted!", 'info')

    session.pop('have_parent_access', None)
    deleted_user = delete_user(g.cur_user, get_children_recursive(g.cur_user))
    if deleted_user:
        db.session.delete(deleted_user)
        db.session.commit()

    return redirect(url_for('main.home'))


@users.route("/sub_accounts")
@login_required
def sub_accounts():
    return render_template('users/sub_accounts.html', title='Sub-accounts',
                           get_children_recursive=get_children_recursive)


@users.route("/create_sub_account", methods=['GET', 'POST'])
@login_required
def create_sub_account():
    form = CreateSubAccountForm()
    if form.validate_on_submit():
        if form.password.data:
            if python_ver == 3.9:
                hashed_password = app_bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            else:
                hashed_password = app_bcrypt.generate_password_hash(form.password.data)
        else:
            hashed_password = ''
        new_user = create_user(username=form.username.data, email=form.email.data, postal_code=form.postal_code.data,
                               hashed_password=hashed_password, parent=g.cur_user)
        db.session.add(new_user)
        db.session.commit()
        flash("'" + new_user.username + "' account has been created!", 'success')
        return redirect(url_for('users.sub_accounts'))

    return render_template('users/create_sub_account.html', title='Create Sub-Account', form=form)


@users.route("/go_to_sub_account/<int:child_id>")
@login_required
def got_to_sub_account(child_id):
    if child_id < 0 or child_id >= len(g.cur_user.children):
        abort(403)

    session['cur_user_id'] = g.cur_user.children[child_id].id
    session['have_parent_access'] = True

    return redirect(url_for('relationships.user_contacts'))


@users.route("/go_to_parent_account")
@login_required
def go_to_parent_account():
    if not g.have_parent_access:
        abort(403)

    session['cur_user_id'] = g.cur_user.parent.id
    session.pop('have_parent_access', None)

    return redirect(url_for('relationships.user_contacts'))


@users.route("/delete_sub_account/<int:child_id>", methods=['POST'])
@login_required
def delete_sub_account(child_id):
    if child_id < 0 or child_id >= len(g.cur_user.children):
        abort(403)

    deleted_user = g.cur_user.children[child_id]
    deleted_user = delete_user(deleted_user, get_children_recursive(deleted_user))
    if deleted_user:
        db.session.delete(deleted_user)
        db.session.commit()

    return redirect(url_for('users.sub_accounts'))


@users.route("/detach_sub_account/<int:child_id>", methods=['POST'])
@login_required
def detach_sub_account(child_id):
    if child_id < 0 or child_id >= len(g.cur_user.children):
        abort(403)

    cur_child = g.cur_user.children[child_id]
    if cur_child.email and cur_child.password:
        cur_child.parent_id = None
        db.session.commit()

    return redirect(url_for('users.sub_accounts'))

covid_web_app/templates/users/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h2 class="account-heading">{{ g.cur_user.username }}</h2>
        <p class="text-secondary">{{ g.cur_user.email }}</p>
        <p class="text-secondary">Account ID: {{ g.cur_user.id }}</p>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.postal_code.label(class="form-control-label") }}

                    {% if form.postal_code.errors %}
                        {{ form.postal_code(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.postal_code.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.postal_code(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete Account</button>
            </div>
        </form>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Account?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% if children_list %}
              <div class="modal-body">
                  <p>
                      {% if children_list|length == 1 %}
                        By deleting your account, the following account will also be deleted:<br><b>
                        <br>&emsp;{{ children_list[0].username }}</b>
                      {% elif 1 < children_list|length %}
                        By deleting your account, the following accounts will also be deleted:<br><b>
                        {% if children_list|length < 11 %}
                            {% for cur_child in children_list %}
                                <br>&emsp;{{ cur_child.username }}
                            {% endfor %}
                        {% else %}
                            {% for cur_child in range(5) %}
                                <br>&emsp;{{ children_list[cur_child].username }}
                            {% endfor %}
                                <br>&emsp;And {{ children_list|length - 5 }} other accounts
                        {% endif %}</b>
                      {% endif %}
                  </p>
              </div>
          {% endif %}
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('users.delete_account') }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

covid_web_app/templates/users/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check-inline">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock %}

covid_web_app/templates/users/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create a New Account</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.postal_code.label(class="form-control-label") }}
                    {% if form.postal_code.errors %}
                        {{ form.postal_code(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.postal_code.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.postal_code(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign In</a>
        </small>
    </div>
{% endblock %}

covid_web_app/templates/users/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

covid_web_app/templates/users/sub_accounts.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        {% if g.cur_user.children %}
            <form method="GET" id="FormContext"></form>
            <ul class="list-group list-group-flush">
                {% for child_id in range(g.cur_user.children|length) %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a class="h3" style="text-decoration: none; color: inherit;" href="{{ url_for('users.got_to_sub_account', child_id=child_id) }}"> {{ g.cur_user.children[child_id].username }}</a>
                        <span class="pull-right">
                            <button type="submit" class="btn btn-primary" formaction="{{ url_for('users.got_to_sub_account', child_id=child_id) }}" form="FormContext">Go To</button>
                            {% if g.cur_user.children[child_id].email and g.cur_user.children[child_id].password %}
                                <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#detachModal{{ child_id }}">Detach</button>
                            {% else %}
                                <button type="button" class="btn btn-outline-secondary" disabled>Detach</button>
                            {% endif %}
                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ child_id }}">Delete</button>
                        </span>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <h3>No sub-account created</h3>
        {% endif %}

        <form action="{{ url_for('users.create_sub_account') }}">
            <input class="btn btn-outline-info mt-3" type="submit" value="Create new sub-account">
        </form>
    </div>

    <!-- Modal -->
    {% for child_id in range(g.cur_user.children|length) %}
        {% set children_list = get_children_recursive(g.cur_user.children[child_id]) %}
        <div class="modal fade" id="deleteModal{{ child_id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ child_id }}" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel{{ child_id }}">Delete '{{ g.cur_user.children[child_id].username }}' account?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {% if children_list %}
                  <div class="modal-body">
                      <p>
                          {% if children_list|length == 1 %}
                            By deleting this account, the following account will also be deleted:<br><b>
                            <br>&emsp;{{ children_list[0].username }}</b>
                          {% elif 1 < children_list|length %}
                            By deleting this account, the following accounts will also be deleted:<br><b>
                            {% if children_list|length < 11 %}
                                {% for cur_child in children_list %}
                                    <br>&emsp;{{ cur_child.username }}
                                {% endfor %}
                            {% else %}
                                {% for cur_child in range(5) %}
                                    <br>&emsp;{{ children_list[cur_child].username }}
                                {% endfor %}
                                    <br>&emsp;And {{ children_list|length - 5 }} other accounts
                            {% endif %}</b>
                          {% endif %}
                      </p>
                  </div>
              {% endif %}
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('users.delete_sub_account', child_id=child_id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade" id="detachModal{{ child_id }}" tabindex="-1" role="dialog" aria-labelledby="detachModalLabel{{ child_id }}" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="detachModalLabel{{ child_id }}">Detach '{{ g.cur_user.children[child_id].username }}' account?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                  By confirming, you will lose direct access to this account.
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('users.detach_sub_account', child_id=child_id) }}" method="POST">
                    <input class="btn btn-warning" type="submit" value="Detach">
                </form>
              </div>
            </div>
          </div>
        </div>
    {% endfor %}
{% endblock %}